### PR TITLE
Make items generic to allow for complex objects to be returned without the need to map display name to a static value

### PR DESCRIPTION
**Pull request by MattWeiler**
I love your component, thank you it was a game changer :)
Feel free to ignore this PR if my changes don't appeal to you.

I don't know if you're interested in my changes as they introduce breaking changes due to the component signature being changed; but I figured that I'd share them.

I needed to tweak the functionality a bit to suit my needs:

- generic type for items
- customizing the colors
- customizing some animation settings

### High Level Changes I Made

1. Updated the items object type from a `string` to a generic type. This allows for complex types to be mapped which is especially useful as the display value doesn't need to be mapped to a constant value upon each time an item is selected. When internationalizing an application, this helps a lot as I don't want to be converting between the display text, in the users language, to some constant value for the selected item.
2. Added a new `props` attribute `colorOverrides` to allow overriding of the default colors previously stored in the `styles.tsx` file; this was done to allow customization for styling purposes.
3. Added a new `props` attribute `sliderAnimationConfig` to allow overriding of the default animation settings (_durations, opacity while sliding animation_).
4. Modified the code to allow the `props.items` and `props.value` to be changed by the parent component, and have those changes reflected.
5. Added comments to the `props`.
6. Bumped the application version from `1.1.1` to `2.0.0` since these changes introduce breaking changes due to the component signature being changed.

### CODE REVIEW

**Comment by alejandrocortell** [comment]
Hi MattWeiler, I really love your work and this push the component to another level.
Thank you!

**Comment by MattWeiler** [comment]
Hi @alejandrocortell 

I'm glad you like it :)

I just noticed that the `/dist` directory contains the `raw JavaScript version` of the component, which is what it looks like `npm` uses.
I'm not sure how you created that last time, so I wasn't able to do so.

If you can share the script that you run, I'm happy to do it :)

**Comment by alejandrocortell** [comment]
Hi MattWeiler
I just run `tsc index.tsx --jsx` to compile typescript.

**Comment by MattWeiler** [comment]
Awesome, thank you.
I've never exported a typescript component before, so it's new to me.

**Pull request merged**
